const a = 10.5;
// console.log(typeof a);
var b = "10";
// console.log(typeof b);
// console.log(a-b);
// console.log(a-parseInt(b));
var c = true;
console.log(typeof c);
var d;
console.log(typeof d);
var d = null;
console.log(typeof d);
var t = 5161215121651626184984941n;
console.log(typeof t);